---
title: "Chapter 2 Carrizo"
output: html_document
---
###Load Data
```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(meta)
library(PRISMAstatement)
library(skimr)
setwd("/R Packages/Chapter 2")
```

```{r}
###Load all necessary .csv files
setwd("/R Packages/Chapter 2")
photo <- read.csv("Carrizo Shrub Photo density Sheet.csv")
focal <- read.csv("Focal Observations Data Sheet.csv")
transect <- read.csv("Transect Data Sheet.csv")
cam.location <- read.csv("Camera Location data Sheet.csv")
```


### Data Set-up
```{r}
###Give Summary of photo data

summary(photo)
```

```{r}
count.hit <- photo %>%
  count(animal.hit) %>%
  na.omit()
summary(count.hit)

###Camera recorded an animal 2.705% of the time. Not too bad
```
```{r}
skim(photo)
```
```{r}
###Transect Data

summary(transect)
```

```{r}
tran.hit <- transect %>%
  count(animal.hit) %>%
  na.omit()
summary(tran.hit)
```

```{r}
skim(transect)
```
```{r}
tran.hit %>%
  ggplot(aes(animal.hit, n)) + geom_col() + theme_classic() + xlab("Hits") + ylab("Count") + ggtitle("Hits during Transects")
```
```{r}
####Summary capture data on Transects
transect.data <- transect %>%
  group_by(Site, Site.Number, Site.Density) %>%
  summarise(captures = sum(animal.hit), n = n(), animal.richness = n_distinct(RTM)-1) %>% mutate(rate = captures/n) #-1 for richness bc of none as level
transect.data$rate <- as.character(transect.data$rate)

###Summary Transect Animal Data
transect.diversity <- transect %>%
  group_by(Site, Site.Number, Site.Density) %>%
  summarise(captures = sum(animal.hit), n = n()) %>% mutate(rate = captures/n)

unique(transect.diversity$Site.Density)
```
```{r}
transect.level <- transect %>%
  group_by(Site, Site.Number, Site.Density, Date) %>%
  summarise(captures = sum(animal.hit), n = n()) %>% mutate(rate = captures/n)

unique(transect.level$Site.Density)
```

```{r}
###Data Viz for number of hits during photo analysis
count.hit %>%
  ggplot(aes(animal.hit, n)) + geom_col() + theme_classic() + xlab("Hits") + ylab("Count") + ggtitle("Number of total animal hits")
```
```{r}
###Summary Capture Data
data <- photo %>%
  group_by(region, site..3.or.4., week, level..l.m.h.none., rep, camera.number) %>%
  summarise(captures = sum(animal.hit), n = n(), animal.richness = n_distinct(RTU)-1) %>% mutate(rate = captures/n) #-1 for richness bc of none as level
data$rep <- as.character(data$rep)

###Summary Animal Data
diversity <- photo %>%
  group_by(region, site..3.or.4., week, rep, RTU) %>%
  summarise(captures = sum(animal.hit), n = n()) %>% mutate(rate = captures/n)

unique(diversity$RTU)
```

```{r}
###Summary level Data
level <- photo %>%
  group_by(region, site..3.or.4., week, rep, level..l.m.h.none.) %>%
  summarise(captures = sum(animal.hit), n = n()) %>% mutate(rate = captures/n)

unique(level$level..l.m.h.none.)
```

```{r}
animals <- photo %>%
  group_by(region, site..3.or.4., week, rep, RTU) %>%
  summarise(captures = sum(animal.hit), n = n()) %>% mutate(rate = captures/n)

unique(animals$RTU)
```


##Data Viz

```{r}
###Total captures between site levels

ggplot(level, aes(level..l.m.h.none., captures)) +
  geom_boxplot() + 
  labs(y = "total captures", x = "site density") + ggtitle("Number of Total Animal Hits in Camera Traps")
```
```{r}
###Capture rate per site level
ggplot(level, aes(level..l.m.h.none., rate)) +
  geom_boxplot() + 
  labs(y = "capture rate", x = "site density")
```


```{r}
ggplot(transect.level, aes(rate, captures, color = Site.Density)) +
         geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  facet_wrap(~Site.Density, scales = "free") +
  labs(color = "", x = "Rate of Capture", y = "total captures")
```
```{r}
require(mgcv)
ggplot(transect.level, aes(rate, captures, color = Site.Density)) +
         stat_smooth(method = "gam") +
  geom_smooth(method = lm, se = FALSE) +
  facet_wrap(~Site.Density, scales = "free") +
  labs(color = "", x = "Rate of Capture", y = "total captures")
```

```{r}
ggplot(transect.level, aes(n, captures, color = Site.Density)) +
         geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  facet_wrap(~Site.Density, scales = "free") +
  labs(color = "", x = "n", y = "total captures")
```
```{r}
require(mgcv)
ggplot(transect.level, aes(n, captures, color = Site.Density)) +
         stat_smooth(method = "gam") +
  geom_smooth(method = lm, se = FALSE) +
  facet_wrap(~Site.Density, scales = "free") +
  labs(color = "", x = "n", y = "total captures")
```

```{r}
ggplot(transect.level, aes(rate, n, color = Site.Density)) +
         geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  facet_wrap(~Site.Density, scales = "free") +
  labs(color = "", x = "Rate of Capture", y = "n")
```
```{r}
require(mgcv)
ggplot(transect.level, aes(n, rate, color = Site.Density)) +
         stat_smooth(method = "gam") +
  geom_smooth(method = lm, se = FALSE) +
  facet_wrap(~Site.Density, scales = "free") +
  labs(color = "", x = "n", y = "rate")
```

```{r}
###Diversity Plot from Photo Data looking at Total Captures
excludes <- c("none", "None", "unidentifiable", "unkown", "", "Unidentifiable", "Human")

plot.diversity <- diversity%>%
  filter(!RTU %in% excludes)

ggplot(plot.diversity, aes(RTU, captures, fill = site..3.or.4.)) +
  geom_bar(stat = "identity") +
  coord_flip() + 
  labs(fill = "", x = "total captures")
```
```{r}
###Diversity Plot from Photo Data looking at Rate
ggplot(plot.diversity, aes(RTU, rate, fill = site..3.or.4.)) +
  geom_bar(stat = "identity") +
  coord_flip() + 
  labs(fill = "", x = "total captures")
```


###Stats
###Stats for capture compare to level
```{r}
m <- glm(captures~level..l.m.h.none., data = level) #capture difference between microsite
summary(m)
```
```{r}
### Test if data is significant
anova(m, test = "Chisq")

####ITS SIGNIFICANT!!!
```
```{r}
shapiro.test(m$residuals)

###Data is not Normally distributed
```
```{r}
library(lsmeans)
lsmeans(m, pairwise~level..l.m.h.none., adjust = "Tukey")
```
```{r}
m <- glm(captures~level..l.m.h.none., data = level, family = "quasipoisson")
summary(m)
```


###Stats for Captures by Site
```{r}
m <- glm(captures~site..3.or.4., data = level) #capture difference between microsite
summary(m)
```
```{r}
anova(m, test = "Chisq")
```
```{r}
ggplot(level, aes(level..l.m.h.none., captures)) +
  geom_boxplot() +
  labs(y = "capture rate", x = "site density")
```

```{r}
m <- glm(rate~site..3.or.4., data = level) #capture difference between microsite
summary(m)
```
```{r}
m <- glm(rate~level..l.m.h.none., data = level) #rate of capture between microsites
summary(m)
```
```{r}
anova(m, test = "Chisq")
```


```{r}
ggplot(level, aes(level..l.m.h.none., rate)) +
  geom_boxplot() +
  labs(y = "capture rate", x = "site density")
```
###Stats for rate of capture between Levels
```{r}
mp <- glm(rate~level..l.m.h.none., data = level, family = "quasipoisson")
summary(mp)
```
```{r}
anova(mp, test = "Chisq")
```
```{r}
shapiro.test(mp$residuals)

###Data is not Normally distributed
```
```{r}
library(lsmeans)
lsmeans(mp, pairwise~level..l.m.h.none., adjust = "Tukey")
```

###Stats for Transect captures
```{r}
###Boxplot for Transect Captures
ggplot(transect.data,  aes(Site.Density, captures)) +
  geom_boxplot() +
  labs(y = "capture rate", x = "site density")
```

```{r}
mt <- glm(captures~Site.Density, data = transect.level)
summary(mt)
```
```{r}
anova(mt, test = "Chisq") #get p-value for model
```
```{r}
shapiro.test(mt$residuals) #explore residuals
```
```{r}
library(lsmeans)
lsmeans(mt, pairwise~Site.Density, adjust = "Tukey")
```
```{r}
mt <- lm(captures~Site.Number, data = transect.level)
summary(mt)
```


```{r}
mt <- glm(rate~Site.Density, data = transect.level)
summary(mt)
```
```{r}
anova(mt, test = "Chisq")
```
