---
title: "Index (Cleaned up work)"
output: html_document
---
```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(meta)
library(PRISMAstatement)
library(skimr)
library(MASS)
library(ggpubr)
library(vegan)
library(emmeans)
setwd("/R Packages/Chapter 2")
```
###Wrangle
```{r}
data.final <- read.csv("data.csv")

density_simple <- data.final %>%
  group_by(as.character(density_levels), density_category, density, microsite, phylum) %>%
  summarise(animals = sum(daily_animal_totals), richness = n()) %>%
  rename(density_levels = 'as.character(density_levels)')

data_simple <- data.final %>%
  group_by(as.character(density_levels), method, density_category, density, microsite) %>%
  summarise(animals = sum(daily_animal_totals), richness = n()) %>%
  rename(density_levels = 'as.character(density_levels)')

density_simple2 <- data.final %>%
  group_by(as.character(density_levels), density_category, density, cover) %>%
  summarise(animals = sum(daily_animal_totals), richness = n()) %>%
  rename(density_levels = 'as.character(density_levels)')
```
```{r}
#RDM Set up
RDM <- read.csv("RDM.CSV")
data_RDM <- RDM %>%
  group_by(as.character(density_level), Site.Density, density, RDM_g, microsite) %>%
  summarise() %>%
  rename(density_level = 'as.character(density_level)')

names(data_RDM)[1] <- "density_levels"
```
```{r}
climate <- read_csv("Carrizo_micronet.csv")
data_climate <- climate %>%
  group_by(as.character(density_level), microsite, temp) %>%
  summarise() %>%
  rename(density_level = 'as.character(density_level)')
names(data_climate)[1] <- "density_levels"

density_simple4 <- data.final %>%
  group_by(as.character(density_levels), microsite) %>%
  summarise(animals = sum(daily_animal_totals), richness = n()) %>%
  rename(density_levels = 'as.character(density_levels)')

animal.climate.data <- merge(data_climate, density_simple4, all = TRUE)
```
```{r}
density_simple5 <- data.final %>%
  group_by(as.character(density_levels), density, microsite, phylum) %>%
  summarise(animals = sum(daily_animal_totals), richness = n()) %>%
  rename(density_levels = 'as.character(density_levels)')

data_RDM2 <- RDM %>%
  group_by(as.character(density_level), density, microsite) %>%
  summarise(RDM = mean(RDM_g)) %>%
  rename(density_level = 'as.character(density_level)')
names(data_RDM2)[1] <- "density_levels"

data_climate2 <- climate %>%
  group_by(as.character(density_level), microsite) %>%
  summarise(mean_temp = mean(temp), max_temp = max(temp)) %>%
  rename(density_level = 'as.character(density_level)')
names(data_climate2)[1] <- "density_levels"

rdm.climate <- merge(data_climate2, data_RDM2, all = TRUE)
final.data <- merge(density_simple5, rdm.climate, all = TRUE)

final.data$sd.animals <- sd(density_simple$animals, na.rm = TRUE)
final.data$sd.richness <- sd(density_simple$richness, na.rm = TRUE)

animal.data <- read.csv("animals.csv")
animal.data.final <- animal.data %>%
  group_by(as.character(species)) %>%
  summarise(number_of_animals = sum(daily_animal_totals)) %>%
  rename(species = "as.character(species)")
```

```{r}
#Vegan Set-up for PCoA
library(vegan)
library(ape)
library(tidyverse)
library(tidyr)
library(dplyr)

data <- read_csv("animals_revised.csv")

#summarize to site/plot/sample unit per row as observation
data <- read_csv("animals_revised.csv") %>%
  group_by(plot, microsite, phylum, species) %>%
  summarise(abundance = sum(daily_animal_totals)) %>%
  na.omit()

#turn into species matrix only
#split species into meaninful groups if needed such as native/exotic, vert/invert, functional roles
vert_species <- data %>%
  filter(phylum == "vertebrate") %>%
  spread(species,abundance) %>%
  ungroup() %>% 
  dplyr::select(-plot, -microsite, -phylum) %>% 
  replace(is.na(.), 0)
dim(vert_species)
env <- read_csv("environment.csv")
dim(env)

##PCA set up for Inverts
data <- read_csv("animals_revised.csv") %>%
  group_by(plot, microsite, phylum, species) %>%
  summarise(abundance = sum(daily_animal_totals)) %>%
  na.omit()
invert_species <- data %>%
  filter(phylum == "invertebrate") %>%
  spread(species, abundance) %>%
  ungroup() %>% 
  dplyr::select(-plot, -microsite, -phylum) %>% 
  replace(is.na(.), 0)
dim(invert_species)
env2 <- read_csv("environment.csv")
dim(env2)
```


###Data Viz
```{r}
ggplot(final.data, aes(density, animals, color = microsite)) +
  geom_point() +
  geom_errorbar(aes(ymin=animals-sd.animals, ymax=animals+sd.animals), width=.2,
                 position=position_dodge(0.05)) +
  facet_wrap(~phylum) +
  scale_x_continuous(breaks = c(0,3,6,9,12)) +
  scale_color_brewer(palette = "Set1") + theme_classic() +
  geom_smooth(method = lm, se = FALSE) + 
  labs(x = "shrub density", y = "animal density")
```
```{r}
#Animal Richness
ggplot(final.data, aes(density, richness, color = microsite)) +
  geom_point() +
  geom_errorbar(aes(ymin=richness-sd.richness, ymax=richness+sd.richness), width=.2,
                 position=position_dodge(0.05)) +
  facet_wrap(~phylum) +
  scale_x_continuous(breaks = c(0,3,6,9,12)) +
  scale_color_brewer(palette = "Set1") + theme_classic() +
  geom_smooth(method = lm, se = FALSE) + 
  labs(x = "shrub density", y = "animal richness")
```
```{r}
m01 <- adonis(vert_species ~ microsite*shrub_density, data = env)
m01
#PCA!!!
dist <- vegdist(vert_species,  method = "bray")

res <- pcoa(dist) #ape library function
p1 <- as.data.frame(res$vectors) %>% 
  dplyr::select(Axis.1, Axis.2) %>%
  bind_cols(env, .)
#PCOA Plots for Verts
ggplot(p1, aes(Axis.1, Axis.2, group = microsite)) +
  geom_point(aes(color = microsite)) +
  geom_text(aes(label=plot),hjust=0, vjust=0, check_overlap = TRUE, nudge_x = 0.01) +
  scale_color_brewer(palette = "Set1") +
  labs(color = "", subtitle = "labels denote plot identity")
ggplot(p1, aes(Axis.1, Axis.2, group = microsite)) +
  geom_point(aes(color = microsite)) +
  geom_text(aes(label=shrub_density),hjust=0, vjust=0, check_overlap = TRUE, nudge_x = 0.01) +
  scale_color_brewer(palette = "Set1") +
  labs(color = "", subtitle = "labels denote shrub density at each plot")
```
```{r}
m04 <- adonis(invert_species ~ microsite*shrub_density, data = env2)
m04
dist <- vegdist(invert_species,  method = "bray")
res <- pcoa(dist) #ape library function
p2 <- as.data.frame(res$vectors) %>% 
  dplyr::select(Axis.1, Axis.2) %>%
  bind_cols(env, .)
#label by site is ok
ggplot(p2, aes(Axis.1, Axis.2, group = microsite)) +
  geom_point(aes(color = microsite)) +
  geom_text(aes(label=plot),hjust=0, vjust=0, check_overlap = TRUE, nudge_x = 0.01) +
  scale_color_brewer(palette = "Set1") +
  labs(color = "", subtitle = "labels denote plot identity")
ggplot(p2, aes(Axis.1, Axis.2, group = microsite)) +
  geom_point(aes(color = microsite)) +
  geom_text(aes(label=shrub_density),hjust=0, vjust=0, check_overlap = TRUE, nudge_x = 0.01) +
  scale_color_brewer(palette = "Set1") +
  labs(color = "", subtitle = "labels denote shrub density at each plot")
```
#Stats Analysis
```{r}
#Stats for animal abundance with density level by micorsite with RDM and mean temp as covariates
m13 <- glm(animals ~ density*microsite+RDM+mean_temp, family = "quasipoisson", data = final.data)
anova(m13, test = "Chisq")
e13 <- emmeans(m13, pairwise~density*microsite+RDM+mean_temp)
e13
#emmeans seems to not yield any data for this
```
```{r}
#Stats for Animal Richness by density level with RDM and mean temp as covariates
m14 <- glm(richness ~ density*microsite+RDM+mean_temp, family = "gaussian", data = final.data)
anova(m14, test = "Chisq")
e14 <- emmeans(m14, pairwise~density*microsite+RDM+mean_temp)
e14
#Again emmeans seems to not work here
```
```{r}
##Stats for Animal Abundance by density level with RDM and max temp as covariates
m15 <- glm(animals ~ density*microsite+RDM+max_temp, family = "quasipoisson", data = final.data)
anova(m15, test = "Chisq")
e15 <- emmeans(m15, pairwise~density*microsite+RDM+max_temp)
e15
#again emmeans yields NA
```
```{r}
##Stats for Animal Richness by density level with RDM and max temp as covariates
m16 <- glm(richness ~ density*microsite+RDM+max_temp, family = "gaussian", data = final.data)
anova(m16, test = "Chisq")
e16 <- emmeans(m16, pairwise~density*microsite+RDM+max_temp)
e16
#Again emmeans yields NA
```
```{r}
#PCOA Stats
m02 <- betadisper(dist, env$microsite)
m02
anova(m02)
permutest(m02, pairwise = TRUE, permutations = 99)
m2.HSD <- TukeyHSD(m02)
boxplot(m02)
m03 <- betadisper(dist, env$shrub_density)
m03
anova(m03)
permutest(m03, pairwise = TRUE, permutations = 99)
m03.HSD <- TukeyHSD(m03)
boxplot(m03)
```


#Appendix Figures
```{r}
#Appendix A Map of Sites
site.4 <- read.csv("Site 4 Data Sheet.csv")
#Map for appendix
library(ggmap)
register_google(key="AIzaSyBpfKtYrkYVS3LEJSjV1cIHeYrxJPsPX4U")
carrizo4 <- get_map(location = c(lon = -119.6283, lat = 35.11985), zoom = 17)
carrizo4
site.wide.map <- ggmap(carrizo4)
site.wide.map <- site.wide.map +
  geom_point(data=site.4, aes(x=shrub.lng, y=shrub.lat), alpha = 3/10, size =4) +
  labs(title = "Site Wide Species Observations", x = "longitude", y = "latitude")
site.wide.map
```

```{r}
site.3 <- read.csv("Site 3 Data Sheet.csv")
#Map for appendix
library(ggmap)
register_google(key="AIzaSyBpfKtYrkYVS3LEJSjV1cIHeYrxJPsPX4U")
carrizo3 <- get_map(location = c(lon = -119.67192, lat = 35.16175), zoom = 17)
carrizo3
site.wide.map <- ggmap(carrizo3)
site.wide.map <- site.wide.map +
  geom_point(data=site.3, aes(x=shrub.lng, y=shrub.lat), alpha = 3/10, size =4) +
  labs(title = "Site Wide Species Observations", x = "longitude", y = "latitude")
site.wide.map
```



```{r}
#Appendix D Species List
list(animal.data.final)
```
```{r}
#Appendix E Contrast of sampling methods
ggplot(data_simple, aes(density_levels, animals, color = method)) +
  geom_boxplot() +
  scale_color_brewer(palette = "Set1") +
  theme_classic() + 
  labs(x = "shrub density level", y = "animal abundance")
```

